export default function handler(req, res) {

  // БАЗА (пока вручную)
const products = [
  { name: "Kale", ii: 5 },
  { name: "Arugula", ii: 5 },
  { name: "Cauliflower", ii: 20 },
  { name: "Bell peppers", ii: 25 },
  { name: "Zucchini", ii: 15 },
  { name: "Brussels sprouts", ii: 15 },
  { name: "Green beans", ii: 25 },
  { name: "Eggplant", ii: 20 },
  { name: "Tomato", ii: 20 },
  { name: "Cucumber", ii: 3 },
  { name: "White cabbage", ii: 15 },
  { name: "Green onion", ii: 10 },
  { name: "Onion", ii: 20 },
  { name: "Parsley", ii: 10 },
  { name: "Dill", ii: 10 },
  { name: "Lettuce", ii: 10 },
  { name: "Garlic", ii: 10 },
  { name: "Spinach", ii: 10 },
  { name: "Broccoli", ii: 11 },
  { name: "Beetroot", ii: 65 },
  { name: "Beetroot (cooked)", ii: 65 },
  { name: "Asparagus", ii: 15 },
  { name: "Mushrooms", ii: 10 },
  { name: "Artichoke", ii: 20 },
  { name: "Rutabaga", ii: 30 },
  { name: "Parsnip", ii: 45 },
  { name: "Radish", ii: 15 },
  { name: "Horseradish", ii: 10 },
  { name: "Celery", ii: 10 },
  { name: "Pumpkin", ii: 70 },
  { name: "Squash", ii: 30 },
  { name: "Leeks", ii: 30 },
  { name: "Fennel", ii: 15 },
  { name: "Carrot", ii: 40 },
  { name: "Sweet Corn", ii: 65 },
  { name: "Bottle gourd", ii: 10 },
  { name: "Peas", ii: 50 },
  { name: "Pickled cucumber", ii: 15 },
  { name: "Leafy greens", ii: 10 },
  { name: "Pears", ii: 50 },
  { name: "Green bananas", ii: 50 },
  { name: "Dates", ii: 80 },
  { name: "Figs", ii: 60 },
  { name: "Plum", ii: 30 },
  { name: "Apricot", ii: 20 },
  { name: "Grapefruit", ii: 22 },
  { name: "Grapes", ii: 82 },
  { name: "Dried fruits", ii: 110 },
  { name: "Watermelon", ii: 72 },
  { name: "Melon", ii: 65 },
  { name: "Prunes", ii: 110 },
  { name: "Dried apricots", ii: 110 },
  { name: "Strawberry", ii: 25 },
  { name: "Blueberry", ii: 25 },
  { name: "Raspberry", ii: 25 },
  { name: "Blackberry", ii: 25 },
  { name: "Currant", ii: 25 },
  { name: "Cherry", ii: 22 },
  { name: "Cherries", ii: 22 },
  { name: "Avocado", ii: 6 },
  { name: "Orange", ii: 60 },
  { name: "Mango", ii: 60 },
  { name: "Banana", ii: 81 },
  { name: "Apple", ii: 59 },
  { name: "Quince", ii: 35 },
  { name: "Pineapple", ii: 60 },
  { name: "Pomegranate", ii: 35 },
  { name: "Guava", ii: 15 },
  { name: "Kiwi", ii: 50 },
  { name: "Coconut", ii: 45 },
  { name: "Lime", ii: 20 },
  { name: "Lychee", ii: 50 },
  { name: "Passion fruit", ii: 30 },
  { name: "Nectarine", ii: 40 },
  { name: "Papaya", ii: 60 },
  { name: "Peach", ii: 35 },
  { name: "Pomelo", ii: 30 },
  { name: "Rambutan", ii: 40 },
  { name: "Physalis", ii: 15 },
  { name: "Persimmon", ii: 50 },
  { name: "Sweet cherry", ii: 25 },
  { name: "Tuna", ii: 25 },
  { name: "Mackerel", ii: 25 },
  { name: "Salmon", ii: 24 },
  { name: "Trout", ii: 25 },
  { name: "Squid", ii: 20 },
  { name: "Shrimp", ii: 20 },
  { name: "Mussels", ii: 20 },
  { name: "Octopus", ii: 20 },
  { name: "Oysters", ii: 20 },
  { name: "Cod", ii: 30 },
  { name: "White fish (generic)", ii: 30 },
  { name: "Haddock", ii: 30 },
  { name: "Prawns", ii: 20 },
  { name: "Crab", ii: 20 },
  { name: "Lobster", ii: 20 },
  { name: "Sardines", ii: 25 },
  { name: "Anchovies", ii: 25 },
  { name: "Pollock", ii: 30 },
  { name: "Swordfish", ii: 30 },
  { name: "Sea bass", ii: 30 },
  { name: "Halibut", ii: 30 },
  { name: "Turkey", ii: 50 },
  { name: "Chicken breast", ii: 49 },
  { name: "Chicken", ii: 49 },
  { name: "Beef", ii: 51 },
  { name: "Pork", ii: 45 },
  { name: "Lamb", ii: 50 },
  { name: "Rabbit", ii: 45 },
  { name: "Duck", ii: 55 },
  { name: "Ham", ii: 46 },
  { name: "Parma ham", ii: 50 },
  { name: "Sausage", ii: 28 },
  { name: "Chicken liver", ii: 19 },
  { name: "Chicken hearts", ii: 19 },
  { name: "Chicken gizzards", ii: 19 },
  { name: "Pork liver", ii: 20 },
  { name: "jamon", ii: 40 },
  { name: "Chicken nuggets", ii: 70 },
  { name: "Kefir", ii: 40 },
  { name: "Tofu", ii: 15 },
  { name: "Yogurt with sugar", ii: 115 },
  { name: "Full-fat yogurt", ii: 80 },
  { name: "0%  yogurt", ii: 100 },
  { name: "2%  yogurt", ii: 90 },
  { name: "Ryazhenka (fermented baked milk)", ii: 98 },
  { name: "Cheese", ii: 45 },
  { name: "Cottage cheese", ii: 45 },
  { name: "Milk", ii: 90 },
  { name: "Skim milk", ii: 98 },
  { name: "Lactose", ii: 50 },
  { name: "Ice cream (vanilla)", ii: 89 },
  { name: "Ayran", ii: 35 },
  { name: "Katyk", ii: 40 },
  { name: "Cream", ii: 25 },
  { name: "Whipping cream", ii: 20 },
  { name: "Sour cream (25% fat)", ii: 40 },
  { name: "Tan", ii: 35 },
  { name: "Almond milk", ii: 20 },
  { name: "Skyr yogurt", ii: 110 },
  { name: "Whey", ii: 140 },
  { name: "Feta cheese", ii: 45 },
  { name: "Powdered milk", ii: 95 },

  { name: "Oats", ii: 40 },
  { name: "Barley", ii: 50 },
  { name: "Bread", ii: 100 },
  { name: "Wholemeal bread", ii: 96 },
  { name: "Whole wheat bread", ii: 96 },
  { name: "Wheat bran", ii: 30 },
  { name: "Pasta (cooked)", ii: 40 },
  { name: "Bulgur (cooked)", ii: 50 },
  { name: "Quinoa (cooked)", ii: 55 },
  { name: "White rice (cooked)", ii: 79 },
  { name: "Brown rice (cooked)", ii: 62 },
  { name: "Black rice (cooked)", ii: 50 },
  { name: "Amaranth", ii: 45 },
  { name: "Couscous", ii: 65 },
  { name: "Spelt", ii: 50 },
  { name: "Sorghum", ii: 55 },
  { name: "Teff", ii: 45 },
  { name: "Farro", ii: 50 },
  { name: "Buckwheat (cooked)", ii: 50 },
  { name: "Tapioca starch", ii: 95 },
  { name: "All-Bran cereal", ii: 60 },
  { name: "Spaghetti (boiled)", ii: 40 },
  { name: "Instant oatmeal", ii: 79 },
  { name: "Oatmeal", ii: 40 },
  { name: "Granola", ii: 70 },

  { name: "Chickpeas", ii: 40 },
  { name: "Hummus", ii: 35 },
  { name: "Lentils", ii: 58 },
  { name: "Fresh soybeans", ii: 20 },
  { name: "Edamame", ii: 50 },
  { name: "Baked beans", ii: 120 },
  { name: "Beans", ii: 40 },
  { name: "Peas", ii: 45 },
  { name: "Mung beans", ii: 30 },
  { name: "Miso paste", ii: 25 },
  { name: "Kidney beans", ii: 40 },
  { name: "Tempeh", ii: 30 },
  { name: "Navy beans", ii: 65 },

  { name: "Peanut butter", ii: 30 },
  { name: "Pecan", ii: 10 },
  { name: "Peanut", ii: 20 },
  { name: "Macadamia nut", ii: 10 },
  { name: "Almond", ii: 20 },
  { name: "Walnut", ii: 20 },
  { name: "Hazelnut", ii: 15 },
  { name: "Brazil nut", ii: 10 },
  { name: "Pine nuts", ii: 15 },
  { name: "Cashew", ii: 25 },
  { name: "Pistachio", ii: 20 },
  { name: "Chia seeds", ii: 30 },
  { name: "Flax seeds", ii: 20 },
  { name: "Sunflower seeds", ii: 35 },
  { name: "Pumpkin seeds", ii: 25 },
  { name: "Cashew", ii: 22 },

  { name: "Honey", ii: 62 },
  { name: "Sugar", ii: 70 },
  { name: "Sucrose", ii: 70 },
  { name: "Jellybeans", ii: 160 },
  { name: "Doughnuts", ii: 74 },
  { name: "Dark chocolate", ii: 22 },
  { name: "Milk chocolate", ii: 120 },
  { name: "Cookie", ii: 92 },
  { name: "Pastry", ii: 82 },
  { name: "Cake", ii: 82 },
  { name: "Cracker", ii: 87 },
  { name: "Croissant", ii: 79 },
  { name: "Popcorn", ii: 54 },
  { name: "Soy sauce", ii: 15 },
  { name: "Stevia", ii: 0 },
  { name: "Saccharin", ii: 0 },
  { name: "Fructose", ii: 30 },
  { name: "Maltodextrin", ii: 110 },
  { name: "Corn syrup", ii: 90 },
  { name: "Maple syrup", ii: 65 },
  { name: "Agave syrup", ii: 90 },
  { name: "Molasses", ii: 100 },
  { name: "Date sugar", ii: 75 },
  { name: "Monk fruit sweetener", ii: 0 },
  { name: "Splenda", ii: 0 },
  { name: "Crackers", ii: 87 },
  { name: "Muffin", ii: 76 },
  { name: "Biscuits (cookies)", ii: 92 },

  { name: "Muesli", ii: 46 },
  { name: "Cornflakes", ii: 118 },
  { name: "Oat flakes", ii: 40 },
  { name: "Shredded wheat", ii: 75 },

  { name: "Chicken egg (boiled)", ii: 31 },
  { name: "Egg (raw)", ii: 31 },
  { name: "Egg (fried)", ii: 31 },

  { name: "Potato (fried)", ii: 90 },
  { name: "French fries", ii: 74 },
  { name: "Potato chips", ii: 90 },
  { name: "Sweet potatoes", ii: 65 },
  { name: "Sweet potato", ii: 65 },
  { name: "Boiled potato", ii: 121 },
  { name: "Potato chip", ii: 115 },
  { name: "Baked potato", ii: 105 },
  { name: "Boiled cooled potatoes", ii: 90 },

  { name: "Strawberry jam", ii: 70 },
  { name: "Raspberry jam", ii: 65 },
  { name: "Cherry jam", ii: 60 },
  { name: "Apricot jam", ii: 70 },
  { name: "Plum jam", ii: 55 },
  { name: "Blueberry jam", ii: 50 },
  { name: "Sea buckthorn jam", ii: 55 },
  { name: "Apple jam", ii: 65 },
  { name: "Pear jam", ii: 60 },
  { name: "Peach jam", ii: 70 },
  { name: "Currant jam", ii: 55 },
  { name: "Feijoa jam", ii: 50 },

  { name: "Red wine dry", ii: 0 },
  { name: "Red wine semisweet", ii: 10 },
  { name: "Red wine sweet", ii: 20 },
  { name: "White wine", ii: 5 },
  { name: "Champagne", ii: 10 },
  { name: "Gin", ii: 0 },
  { name: "Pepsi Cola", ii: 90 },
  { name: "Pepsi", ii: 90 },
  { name: "Coca-Cola", ii: 90 },
  { name: "Coke", ii: 90 },
  { name: "Orange juice", ii: 70 },
  { name: "Apple juice", ii: 65 },
  { name: "Grape juice", ii: 75 },
  { name: "Cranberry juice", ii: 60 },
  { name: "Pineapple juice", ii: 75 },
  { name: "Mango juice", ii: 75 },
  { name: "Tomato juice", ii: 38 },
  { name: "Espresso (no sugar)", ii: 5 },
  { name: "Cappuccino (no sugar)", ii: 40 },
  { name: "Latte (no sugar)", ii: 45 },
  { name: "Flat white (no sugar)", ii: 35 },
  { name: "Raf coffee (no added sugar)", ii: 60 },
  { name: "Decaf coffee (no sugar)", ii: 5 },

  { name: "Seaweed", ii: 20 },
  { name: "Mayonnaise", ii: 5 },
  { name: "Olives", ii: 15 },
  { name: "Seitan", ii: 20 },
  { name: "Coconut butter", ii: 5 },
  { name: "Coconut milk", ii: 7 },
  { name: "Goat milk", ii: 85 },
  { name: "Falafel", ii: 40 },
  { name: "Pizza", ii: 80 },

  { name: "Wheat flour (refined)", ii: 80 },
  { name: "White flour products", ii: 100 },
  { name: "Whole wheat flour", ii: 70 },
  { name: "Almond flour", ii: 7 },
  { name: "Coconut flour", ii: 15 },

  { name: "Butter", ii: 3 },
  { name: "Margarine", ii: 3 },
  { name: "Olive oil", ii: 3 },
  { name: "Coconut oil", ii: 3 }
];

  const q = (req.query.q || "").toLowerCase();

  const result = products.filter(p =>
    p.name.toLowerCase().includes(q)
  );

  res.setHeader("Access-Control-Allow-Origin", allowedOrigin);

  res.status(200).json(result);
}
